- name: File Variables in Ansible 
  hosts: local 
  connection: local 
  vars_files:
    - info.yaml


  tasks:
    - name: Print User Information 
      ansible.builtin.debug:
        msg: "My Name is {{ Name }}, My Age is {{ Age }}"